//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JalkaHoitola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Recieved_ammount = new HashSet<Recieved_ammount>();
        }
    
        public int ProductId { get; set; }
        public string Nmae { get; set; }
        public string Description { get; set; }
        public string Quantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public int GroupId { get; set; }
    
        public virtual ProductGroups ProductGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recieved_ammount> Recieved_ammount { get; set; }
    }
}
